cc_library (
    name = "tftree2",
    hdrs = glob([
        "include/**/*.h",
        "include/**/*.hpp",
    ]),
    srcs = glob([
        "src/**/*.cpp",
    ]),
    copts = ["-Itf2/include",],
    deps = [],
)
